enum TrackerVariant {
	TEMPERATURE_GRADIENT = 'TEMPERATURE_GRADIENT',
	BLACK_AND_WHITE_GRADIENT = 'BLACK_AND_WHITE_GRADIENT',
	ORANGE_TRANSPARENT = 'ORANGE_TRANSPARENT',
}
export default TrackerVariant
